# Generated by Django 3.1.7 on 2021-03-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_model', models.CharField(choices=[('A3', 'A3'), ('S3', 'S3'), ('RS3', 'RS3'), ('A4', 'A4'), ('S4', 'S4'), ('RS4', 'RS4'), ('A5', 'A5'), ('S5', 'S5'), ('A6', 'A6'), ('S6', 'S6'), ('A7', 'A7'), ('A8', 'A8'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q5', 'Q5'), ('SQ5', 'SQ5'), ('Q7', 'Q7'), ('SQ7', 'SQ7'), ('Q8', 'Q8')], max_length=5)),
                ('Engine_type', models.CharField(choices=[('1.4 TFSI', '1.4 TFSI'), ('1.4 FSI', '1.4 FSI'), ('1.6 TFSI', '1.6 TFSI'), ('1.6 FSI', '1.6 FSI'), ('1.8 TFSI', '1.8 TFSI'), ('1.8 FSI', '1.8 FSI'), ('2.0 TFSI', '2.0 TFSI'), ('2.0 FSI', '2.0 FSI'), ('2.4 V6', '2.4 V6'), ('2.6 V6', '2.6 V6')], max_length=10)),
                ('Model_year', models.IntegerField(blank=True, choices=[(2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)])),
                ('Name_of_part', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Available', models.BooleanField(default=True)),
            ],
        ),
    ]
