# Generated by Django 3.1.7 on 2021-03-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chasis', '0002_auto_20210325_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodypart',
            options={'ordering': ['Available']},
        ),
        migrations.AddField(
            model_name='bodypart',
            name='Transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('DSG', 'DSG'), ('Tiptronic', 'Tiptronic')], default='Manual', max_length=15),
        ),
        migrations.AlterField(
            model_name='bodypart',
            name='Description',
            field=models.TextField(null=True),
        ),
    ]
