# Generated by Django 3.1.7 on 2021-03-25 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Engine',
            new_name='EnginePart',
        ),
    ]
