# Generated by Django 3.1.7 on 2021-03-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wheels', '0002_auto_20210325_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wheelpart',
            options={'ordering': ['Available']},
        ),
    ]
