# Generated by Django 3.1.7 on 2021-03-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheels', '0003_auto_20210325_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheelpart',
            name='Transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('DSG', 'DSG'), ('Tiptronic', 'Tiptronic')], default='Manual', max_length=15),
        ),
        migrations.AlterField(
            model_name='wheelpart',
            name='Description',
            field=models.TextField(null=True),
        ),
    ]
