# Generated by Django 3.1.7 on 2021-03-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheels', '0004_auto_20210325_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheelpart',
            name='Engine_type',
            field=models.CharField(choices=[('1.4 TFSI', '1.4 TFSI'), ('1.4 FSI', '1.4 FSI'), ('1.6 TFSI', '1.6 TFSI'), ('1.6 FSI', '1.6 FSI'), ('1.8 TFSI', '1.8 TFSI'), ('1.8 FSI', '1.8 FSI'), ('2.0 TFSI', '2.0 TFSI'), ('2.0 FSI', '2.0 FSI'), ('2.4 V6', '2.4 V6'), ('2.6 V6', '2.6 V6'), ('3.0 FSI', '3.0 FSI'), ('3.0 TFSI', '3.0 TFSI'), ('3.0 V6', '3.0 V6')], max_length=10),
        ),
    ]
