# Generated by Django 3.1.7 on 2021-03-28 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wheels', '0005_auto_20210327_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheelpart',
            name='Created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
