# Generated by Django 3.1.7 on 2021-03-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheels', '0006_wheelpart_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheelpart',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
    ]
