# Generated by Django 3.1.7 on 2021-03-31 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wheels', '0008_auto_20210329_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wheelpart',
            options={'ordering': ['Created_date']},
        ),
        migrations.RemoveField(
            model_name='wheelpart',
            name='Available',
        ),
    ]
